// Checksum: 4467aff984dcfa8872ea02f8d31ff4dd2223dfc66f96afc108f21b2fa1d7a849

// Canonical Reference: CVM-OBJ-001 (blueprint.execution.execution)
// Owner: CVM Team
// UUID: 600e8400-e29b-41d4-a716-446655440400
// Layer: CVM
// Type: object

using System;
using System.Collections.Generic;

namespace Blueprint.CVM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "CVM Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "CVM Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
