// Checksum: c091c86b5189270d4c7a51625b9fa4a7b43efd1df98beb643ca30e5bbaddffd0

// Canonical Reference: BEA-CONTRACT-005 (blueprint.contract.memory)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440604
// Layer: BEA
// Type: contract

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
