// Checksum: 51f14eb025dd86a811d431fab03bd11edd0ec4005cfdeb1cbbf354af53927715

// Canonical Reference: CVM-INV-003 (blueprint.invariant.memory_consistency)
// Owner: CVM Team
// UUID: 600e8400-e29b-41d4-a716-446655441402
// Layer: CVM
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.CVM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "CVM Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "CVM Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
