// Checksum: 7cf328ea78f024480d0533d6cc4a0e4db5d1481e7a3441604a79b08060e5f8a3

// Canonical Reference: BEA-FB-002 (blueprint.forbidden.multiple_ownership)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655442001
// Layer: BEA
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
