// Checksum: 447e2d6bd7930cdfbb17a3958f632354be6d99d3917ea7d2921bfa10362b837f

// Canonical Reference: BEA-CONTRACT-008 (blueprint.contract.profiling)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440608
// Layer: BEA
// Type: contract

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
