// Checksum: 34003f059b610ca0561e4a85909538b71e0f78ab860e680922d28d07ef4fa2c9

// Canonical Reference: COS-OBJ-001 (blueprint.runtime.session)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440300
// Layer: COS
// Type: object

using System;
using System.Collections.Generic;

namespace Blueprint.COS
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
