// Checksum: e6bfb4325d161dbd521d9ccc01d94942c9c91013fab29f751c054719609a110c

// Canonical Reference: BEA-INV-001 (blueprint.invariant.single_source_of_truth)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655441100
// Layer: BEA
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
