import { InMemoryDecisionTraceStore } from "../trace/InMemoryDecisionTraceStore";
import {
  BaseSelectorContext,
  ObjectiveSelectorContext,
} from "../selectors/shared/selectorContext";
import { selectTopic, TopicSelectorConfig } from "../selectors/TopicSelector";
import {
  selectDifficulty,
  DifficultySelectorConfig,
} from "../selectors/DifficultySelector";
import { selectObjective } from "../selectors/ObjectiveSelector";
import { RuntimeClock } from "../../utils/clock";
import { TopicGraphSnapshot } from "../../types/graph";
import { PromptBudgetResult } from "../../types/prompt";
import { DEFAULT_SELECTOR_WEIGHTS } from "../selectors/shared/selectorWeights";
import { deepFreeze } from "@core/freeze/deepFreeze";

// Mock clock for deterministic timestamps
class MockClock implements RuntimeClock {
  private time = 1000;
  now() {
    return this.time;
  }
  advance(ms: number) {
    this.time += ms;
  }
}

describe("Selector Pipeline Integration", () => {
  let traceStore: InMemoryDecisionTraceStore;
  let clock: MockClock;
  let baseCtx: BaseSelectorContext;
  let mockSnapshot: TopicGraphSnapshot;
  let mockBudget: PromptBudgetResult;
  let topicConfig: TopicSelectorConfig;
  let difficultyConfig: DifficultySelectorConfig;

  beforeEach(() => {
    traceStore = new InMemoryDecisionTraceStore();
    clock = new MockClock();
    baseCtx = deepFreeze({
      interviewPhase: "technical",
      remainingTimeMs: 1800000,
      clock,
    });
    mockBudget = {
      tokenBudget: 1000,
      maxCompletionTokens: 500,
      maxContextTokens: 1500,
    } as any;
    topicConfig = { explorationFactor: 1.0 };
    difficultyConfig = {
      weights: DEFAULT_SELECTOR_WEIGHTS,
      maxTimeMs: 3600000,
    };

    mockSnapshot = deepFreeze({
      version: "1.0.0",
      rootTopicId: "react",
      nodes: [
        {
          id: "react",
          saturationScore: 0,
          priorityScore: 1,
          noveltyScore: 0.5,
        },
        {
          id: "hooks",
          saturationScore: 0,
          priorityScore: 0.8,
          noveltyScore: 0.8,
        },
      ],
    }) as any;
  });

  const runPipeline = (signals: Partial<ObjectiveSelectorContext>) => {
    // 1. Topic Selector
    const topicCtx = selectTopic(
      baseCtx,
      mockSnapshot,
      mockBudget,
      topicConfig,
      traceStore,
    );

    // Merge in signals for difficulty
    const diffInputCtx = deepFreeze({ ...topicCtx, ...signals }) as any;

    // 2. Difficulty Selector
    const diffCtx = selectDifficulty(
      diffInputCtx,
      difficultyConfig,
      traceStore,
    );

    // Merge in signals for objective
    const objInputCtx = deepFreeze({ ...diffCtx, ...signals }) as any;

    // 3. Objective Selector
    const objCtx = selectObjective(objInputCtx, traceStore);

    return { topicCtx, diffCtx, objCtx };
  };

  test("Fatigued candidate triggers explore_topic objective and caps difficulty", () => {
    const { objCtx } = runPipeline({
      fatigueScore: 0.9, // above 0.8 threshold
      contradictionScore: 0.1,
      communicationConfidence: 0.8,
      hesitationScore: 0.2,
    });

    expect(objCtx.objective).toBe("explore_topic");
    const events = traceStore.getEvents();
    expect(events).toHaveLength(3);

    // Check immutability
    expect(Object.isFrozen(events[0])).toBe(true);
    expect(events[2].selector).toBe("objective");
    expect(events[2].chosen).toBe("explore_topic");
    expect(events[2].reasons[0]).toContain("fatigue threshold exceeded");
  });

  test("Contradictory candidate triggers challenge_claim objective", () => {
    const { objCtx } = runPipeline({
      fatigueScore: 0.2,
      contradictionScore: 0.8, // above 0.7 threshold
      communicationConfidence: 0.8,
      hesitationScore: 0.1,
    });

    expect(objCtx.objective).toBe("challenge_claim");
    const events = traceStore.getEvents();
    expect(events[2].chosen).toBe("challenge_claim");
  });

  test("Overconfident/novelty candidate gets detect_depth", () => {
    const { objCtx } = runPipeline({
      fatigueScore: 0.1,
      contradictionScore: 0.1,
      communicationConfidence: 0.9,
      hesitationScore: 0.1,
      noveltyScore: 0.8, // high novelty
    });

    expect(objCtx.objective).toBe("detect_depth");
    const events = traceStore.getEvents();
    expect(events[2].chosen).toBe("detect_depth");
  });

  test("Hesitant/low-confidence candidate gets measure_confidence", () => {
    const { objCtx } = runPipeline({
      fatigueScore: 0.1,
      contradictionScore: 0.1,
      communicationConfidence: 0.2,
      hesitationScore: 0.8,
      // topicConfidence and difficultyConfidence are computed internally.
      // We will override them for this test.
    });

    // Actually, topicConfidence and difficultyConfidence are generated by selectors.
    // If we want to simulate measure_confidence from low upstream confidence, we need the selectors to output low confidence.
    // We can just verify it works if we directly call selectObjective with low upstream confidence.
    const customCtx = deepFreeze({
      ...baseCtx,
      selectedTopic: "react",
      topicConfidence: 0.2,
      selectedDifficulty: "intermediate" as any,
      difficultyConfidence: 0.2,
    }) as any;

    const result = selectObjective(customCtx, traceStore);
    expect(result.objective).toBe("measure_confidence");
  });

  test("Trace events are completely deterministic", () => {
    const run1 = runPipeline({ fatigueScore: 0.2, contradictionScore: 0.2 });
    const events1 = traceStore.getEvents();

    traceStore = new InMemoryDecisionTraceStore();
    clock = new MockClock();
    baseCtx = deepFreeze({
      interviewPhase: "technical",
      remainingTimeMs: 1800000,
      clock,
    });

    const run2 = runPipeline({ fatigueScore: 0.2, contradictionScore: 0.2 });
    const events2 = traceStore.getEvents();

    expect(events1).toEqual(events2);
  });
});
