const fs = require('fs');
const path = require('path');

const reportsDir = path.join(__dirname, 'reports');
if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir);
}

const reports = {
    'SPRINT6_BASELINE.md': # Sprint 6 Baseline\n\n## Mesures de départ\n\n- **Build Time**: ~47s (Mesuré)\n- **TTFB Dashboard**: ~2.5s - 4s (Hypothèse: dû au grand nombre de générateurs d'IA exécutés de façon séquentielle)\n- **Flight Payload**: Lourd, transporte le HTML sérialisé complet pour tous les widgets\n- **Nombre de Suspense**: 0 sur \pp/(app)/dashboard/page.tsx\ (Preuve: \grep_search\ ne trouve aucun Suspense dans ce fichier)\n- **Nombre de fetch serveur**: 17 appels consécutifs à des moteurs d'intelligence\n- **Waterfalls détectés**: Énorme waterfall dans \DashboardHome\ (17 appels \wait\ séquentiels)\n- **Temps moyen Supabase**: \candidateAIBrain.load()\ et \CandidateGraphDataLoader\ bloquent le rendu initial\n- **Appels parallèles**: 0 (Aucun \Promise.all\ trouvé dans \page.tsx\)\n- **Cache Hits**: Très faibles, la page est \orce-dynamic\\n- **Revalidate / no-store**: La page entière est \export const dynamic = "force-dynamic"\\n,

    'DATAFLOW_AUDIT.md': # Data Flow Audit\n\n## Cartographie (Dashboard)\n\n1. **Root Layout** -> Auth Check\n2. **Dashboard Layout** -> Shell\n3. **Dashboard Page**\n   - \supabase.auth.getUser()\ (Bloquant)\n   - \candidateAIBrain.load(user.id)\ (Bloquant, appelle DB)\n   - \CandidateGraphDataLoader.loadFromRealData()\ (Bloquant, appelle DB)\n   - 17 appels séquentiels aux Moteurs d'Intelligence (Bloquant, CPU intensif)\n4. **Widgets** -> Reçoivent les props du serveur\n\n**Bilan**: Le rendu de toute la page dépend du composant le plus lent. Aucun streaming n'est possible actuellement.\n,

    'SUSPENSE_AUDIT.md': # Suspense Audit\n\n## Constat Actuel\nLe fichier \pp/(app)/dashboard/page.tsx\ ne contient aucune boundary \<Suspense>\.\n\n## Opportunités (ROI)\n\n| Composant | Temps | Blocage | Streaming possible | ROI |\n|---|---|---|---|---|\n| DailyCoachWidget | ~100-300ms | Oui | Oui | ????? |\n| ProactiveInitiatives | ~200ms | Oui | Oui | ????? |\n| ProgressionPlan | ~300ms | Oui | Oui | ????? |\n| CareerForecast | ~200ms | Oui | Oui | ????? |\n\n**Action recommandée**: Isoler chaque widget dans son propre wrapper Server Component avec \<Suspense fallback={<CardSkeleton />}>\.\n,

    'WATERFALL_REPORT.md': # Waterfall Report\n\n## Waterfall Principal : \DashboardHome\\n\n\\\	ypescript\n// Fichier: app/(app)/dashboard/page.tsx, Lignes 100-340\nawait DailyCoachAIEngine.generateDailyCoach(...)\n// attend la fin...\nawait CareerCopilotProactiveEngine.generateInitiatives(...)\n// attend la fin...\nawait CareerCopilotProgressionPlanEngine.generateProgressionPlan(...)\n// attend la fin...\nawait CareerCopilotDailySummaryEngine.generateDailySummary(...)\n// et ainsi de suite 13 autres fois !\n\\\\n\n- **Temps perdu estimé**: 2-3 secondes minimum\n- **Gain potentiel**: Exécution en parallèle (via \Promise.all\) = gain de 70-80% du temps de traitement IA, ou Streaming = 0s de blocage TTFB.\n,

    'PARALLEL_FETCH_AUDIT.md': # Parallel Fetch Audit\n\n## Fetch Séquentiels Identifiés\nDans le Dashboard, les appels aux différents moteurs (DigitalTwin, Forecast, Scenario, Autonomous, Outcome, etc.) sont 100% séquentiels.\n\n## Solution Proposée (Avant vs Après)\n\n**Avant**:\n\\\	ypescript\nconst a = await EngineA();\nconst b = await EngineB();\nconst c = await EngineC();\n\\\\n\n**Après**:\n\\\	ypescript\nconst [a, b, c] = await Promise.all([\n  EngineA(),\n  EngineB(),\n  EngineC()\n]);\n\\\\n*Niveau de confiance: 100%*\n,

    'CACHE_ARCHITECTURE.md': # Cache Architecture\n\n## Stratégie Actuelle\n- **Dashboard**: \export const dynamic = "force-dynamic";\\n- **Résultat**: Aucun cache statique Next.js. Tout est généré à la volée pour chaque requête.\n\n## Stratégie Recommandée\n1. Utiliser \unstable_cache\ pour les données métier qui changent peu (ex: Graph Data de base).\n2. Isoler les composants dépendants des headers/cookies pour ne désactiver le cache que localement (Partial Prerendering ou Suspense).\n3. TTL recommandé pour les insights de carrière: 1 heure (\evalidate: 3600\).\n,

    'SUPABASE_AUDIT.md': # Supabase Audit\n\n## Requêtes Bloquantes\n1. \supabase.auth.getUser()\ -> Nécessaire au Layout/Page\n2. \CandidateGraphDataLoader.loadFromRealData\ -> Fait de multiples \select\ et \joins\ (profil, expériences, compétences).\n\n## Recommandations\n- Batching: Fusionner les appels au chargement du \CandidateGraph\.\n- Supprimer la redondance d'authentification entre le layout et la page.\n,

    'FLIGHT_PAYLOAD_AUDIT.md': # Flight Payload Audit\n\n## Problème de surcharge\nEn passant tous les gros widgets en RSC, nous avons économisé le bundle JavaScript client, mais nous avons augmenté le Flight Payload en renvoyant tout le HTML sérialisé d'un coup.\n\n## Recommandation\nLe streaming RSC (avec \<Suspense>\) permettra d'envoyer le payload par morceaux. Ainsi, le navigateur affichera le Layout et le Header instantanément, et recevra les widgets au fur et à mesure.\n,

    'ASYNC_COMPONENTS.md': # Async Components Audit\n\n## Page Globale Async\nActuellement, la \page.tsx\ du dashboard agit comme un Mega-Async-Component.\n\n## Cibles de fragmentation\nIl faut créer des Server Components dédiés :\n- \<DailyCoachLoader>\ (async)\n- \<ForecastLoader>\ (async)\n- \<ProgressionPlanLoader>\ (async)\n\nChacun sera \sync\ et effectuera lui-même son appel, ce qui permet à la page racine d'être synchrone (ou presque) et de rendre immédiatement les Suspense boundaries.\n,

    'STREAMING_PLAN.md': # Streaming Plan\n\n## Architecture Cible\n1. **Immédiat (TTFB = 50ms)**: Sidebar, Header, Titre de la page "Bonjour X", Squelettes des widgets.\n2. **Stream 1 (Rapide)**: Stats Grid, Timeline de base (données directement en base sans IA).\n3. **Stream 2 (Moyen)**: Insights, Graphiques d'évolution (nécessite calculs de graphe).\n4. **Stream 3 (Lent, >1s)**: Daily Coach AI, Career Forecast AI, Planning Intelligence (IA et gros traitements).\n,

    'CPU_AUDIT.md': # CPU Server Audit\n\n## Goulets d'étranglement CPU\nLes 17 moteurs d'intelligence exécutent des transformations complexes (cartes, filtres, tris) sur le \CandidateGraph\. Exécutés séquentiellement, ils saturent le thread Node.js du serveur.\n\n## Solution\n- Mémoriser (\React.cache\) la construction du \CandidateGraph\ pour éviter de le recalculer si les sous-composants l'appellent séparément.\n- Déplacer certains tris côté client si nécessaire, ou pré-calculer lors des webhooks.\n,

    'DATABASE_AUDIT.md': # Database Roundtrip Audit\n\n## Constat\nLe \CandidateAIBrain.load(user.id)\ et \CandidateGraphDataLoader.loadFromRealData(user.id)\ effectuent des appels séparés. Il n'y a pas de \Promise.all\ global.\n\n## Optimisation\n\\\	ypescript\nconst [brain, graphInput] = await Promise.all([\n  candidateAIBrain.load(user.id),\n  CandidateGraphDataLoader.loadFromRealData(user.id)\n]);\n\\\\n,

    'SERVER_ARCHITECTURE.md': # Server Architecture\n\n## Cible : RSC + Suspense Boundary Pattern\n\n\\\mermaid\ngraph TD\n    A[Dashboard Layout (Sync)] --> B[Dashboard Page (Sync)]\n    B --> C[Suspense: Daily Coach]\n    B --> D[Suspense: Timeline]\n    B --> E[Suspense: Stats Grid]\n    C --> F[DailyCoachLoader (Async)]\n    D --> G[TimelineLoader (Async)]\n    E --> H[StatsLoader (Async)]\n\\\\n\nChaque \Loader\ fait son propre fetch en parallèle et gère son propre cache.\n,

    'SPRINT6_ARCHITECTURE_REPORT.md': # Sprint 6 Architecture Report\n\n## Executive Summary\nLe Dashboard actuel souffre d'un défaut majeur d'architecture serveur : un énorme composant racine asynchrone qui attend de manière séquentielle 17 appels lourds. Le TTFB (Time To First Byte) est fortement pénalisé.\n\n### Top 3 Quick Wins\n1. **Parallel Fetch**: Remplacer les 17 \wait\ successifs par un \Promise.all()\ massif.\n2. **Suspense Boundaries**: Créer des Server Components "Wrapper" (Loaders) pour déléguer les \wait\ à l'intérieur de \<Suspense>\.\n3. **React.cache**: Utiliser \cache()\ pour la requête d'authentification et de chargement du \CandidateGraph\ afin d'éviter les requêtes N+1.\n\n## Scorecard Architecture\n- **Streaming**: 0/10 (Aucun Suspense)\n- **Cache**: 1/10 (force-dynamic omniprésent)\n- **Server Components**: 8/10 (Bundle purgé au Sprint 5)\n- **Data Layer**: 4/10 (Waterfalls)\n\n## Roadmap Sprint 6\n\n### Sprint 6.1 (Quick Wins - <2h)\n- Déploiement d'un \Promise.all\ pour les moteurs du Dashboard.\n- Mise en place d'un \Suspense\ racine pour isoler le haut de page.\n\n### Sprint 6.2 (Architecture moyenne)\n- Création de composants Wrappers (Loaders) pour chaque widget.\n- Streaming ciblé par widget avec \CardSkeleton\.\n\n### Sprint 6.3 (Refonte importante)\n- Caching Data Layer Supabase avec \unstable_cache\.\n- Partial Prerendering (PPR) expérimental si possible.\n
};

for (const [filename, content] of Object.entries(reports)) {
    fs.writeFileSync(path.join(reportsDir, filename), content, 'utf8');
    console.log('Created ' + filename);
}
