// Checksum: 8244c237bfad1e22d3bd71cf8c7eeb2e2b8034ae62e9ade3b1cd466f9c14de47

// Canonical Reference: COS-OBJ-004 (blueprint.runtime.answer)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440303
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
