// Checksum: b8e55288c29ca1b98a1f4ed7d44e3b807524752db56e296a941a7339ee4ccbcc

// Canonical Reference: COS-OBJ-006 (blueprint.runtime.capability)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440305
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
