// Checksum: 37862e94195c6f6d6948d40bf244903e83f60fbabcb05a67006b3159efc56d95

// Canonical Reference: COS-OBJ-010 (blueprint.runtime.featureflag)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440309
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
