// Checksum: 79290d38062ef4993398fa2bd4188ec6c11c51fd369a0ac899f1a62547a1575e

// Canonical Reference: COS-OBJ-003 (blueprint.runtime.question)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440302
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
