// Checksum: cc2c9ff6b35ae934c814e225d19a350993bbbe6c546717b13d2f66173412a3e2

// Canonical Reference: BEA-OBJ-001 (blueprint.system.version)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440500
// Layer: BEA
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
