// Checksum: 1a8b5710bd3454bf4d103f40686dc1b440d501cdbada469d4c3c4fe427cf03ed

// Canonical Reference: BEA-INV-003 (blueprint.invariant.acyclic_dependencies)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655441102
// Layer: BEA
// Type: unknown

package blueprint

import (
    "github.com/google/uuid"
)

type  struct {
    ID      string                 `json:"id"`
    Name    string                 `json:"name"`
    Owner   string                 `json:"owner"`
    Version string                 `json:"version"`
    Extra   map[string]interface{} `json:"extra"`
}

type Input struct {
    Name    string                 `json:"name"`
    Owner   *string                `json:"owner,omitempty"`
    Version *string                `json:"version,omitempty"`
    Extra   map[string]interface{} `json:"extra,omitempty"`
}

func New(input Input) * {
    owner := "Enterprise Chief Architect"
    if input.Owner != nil {
        owner = *input.Owner
    }
    
    version := "1.0.0"
    if input.Version != nil {
        version = *input.Version
    }
    
    return &{
        ID:      uuid.New().String(),
        Name:    input.Name,
        Owner:   owner,
        Version: version,
        Extra:   input.Extra,
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
