// Checksum: 3d742c38b442ce1ebfc7006246059f8b97b1f23b4d49503ab2e13c36e4d4d2d0

// Canonical Reference: BCM-OBJ-007 (blueprint.cognitive.hypothesis)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440206
// Layer: BCM
// Type: object

package blueprint

import (
    "github.com/google/uuid"
)

type  struct {
    ID      string                 `json:"id"`
    Name    string                 `json:"name"`
    Owner   string                 `json:"owner"`
    Version string                 `json:"version"`
    Extra   map[string]interface{} `json:"extra"`
}

type Input struct {
    Name    string                 `json:"name"`
    Owner   *string                `json:"owner,omitempty"`
    Version *string                `json:"version,omitempty"`
    Extra   map[string]interface{} `json:"extra,omitempty"`
}

func New(input Input) * {
    owner := "Chief Cognitive Architect"
    if input.Owner != nil {
        owner = *input.Owner
    }
    
    version := "1.0.0"
    if input.Version != nil {
        version = *input.Version
    }
    
    return &{
        ID:      uuid.New().String(),
        Name:    input.Name,
        Owner:   owner,
        Version: version,
        Extra:   input.Extra,
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
