// Checksum: 3077fa94346c3990d02a7c2529c6ae15090af6a34c6ad59d0830f92d51e13e2b

// Canonical Reference: BCM-EVT-021 (blueprint.event.reasoning.started)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440720
// Layer: BCM
// Type: event

package com.blueprint.bcm;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class  {
    private String id;
    private String name;
    private String owner;
    private String version;
    private Map<String, Object> extra;

    public () {
        this.extra = new HashMap<>();
    }

    public (String name, String owner, String version) {
        this();
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.owner = owner != null ? owner : "Chief Cognitive Architect";
        this.version = version != null ? version : "1.0.0";
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getOwner() { return owner; }
    public void setOwner(String owner) { this.owner = owner; }
    
    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }
    
    public Map<String, Object> getExtra() { return extra; }
    public void setExtra(Map<String, Object> extra) { this.extra = extra; }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
