// Checksum: 3724c95dfce0560bbebcaf2984e3e598d1cae477d145fe4ff12392c620aa99c4

// Canonical Reference: COS-OBJ-001 (blueprint.runtime.session)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440300
// Layer: COS
// Type: object

package com.blueprint.cos;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class  {
    private String id;
    private String name;
    private String owner;
    private String version;
    private Map<String, Object> extra;

    public () {
        this.extra = new HashMap<>();
    }

    public (String name, String owner, String version) {
        this();
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.owner = owner != null ? owner : "COS Team";
        this.version = version != null ? version : "1.0.0";
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getOwner() { return owner; }
    public void setOwner(String owner) { this.owner = owner; }
    
    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }
    
    public Map<String, Object> getExtra() { return extra; }
    public void setExtra(Map<String, Object> extra) { this.extra = extra; }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
