// Checksum: ecd138c93351e77199c697f5cee282120b7af611c5890b4bcdf20bdf8d584c11

// Canonical Reference: COS-FB-001 (blueprint.forbidden.cos_violation)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655442200
// Layer: COS
// Type: unknown

use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct  {
    pub id: Uuid,
    pub name: String,
    pub owner: String,
    pub version: String,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Input {
    pub name: String,
    pub owner: Option<String>,
    pub version: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

impl  {
    pub fn new(input: Input) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: input.name,
            owner: input.owner.unwrap_or_else(|| "COS Team".to_string()),
            version: input.version.unwrap_or_else(|| "1.0.0".to_string()),
            extra: input.extra,
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
