// Checksum: d255d16ac434eeca96d058107dbcbf947fdb104d2e3c5d3852df6fe4b3fe761f

// Canonical Reference: BCM-OBJ-005 (blueprint.cognitive.knowledge)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440204
// Layer: BCM
// Type: object

use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct  {
    pub id: Uuid,
    pub name: String,
    pub owner: String,
    pub version: String,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Input {
    pub name: String,
    pub owner: Option<String>,
    pub version: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

impl  {
    pub fn new(input: Input) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: input.name,
            owner: input.owner.unwrap_or_else(|| "Chief Cognitive Architect".to_string()),
            version: input.version.unwrap_or_else(|| "1.0.0".to_string()),
            extra: input.extra,
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
