// Checksum: 40403d3d72803f622a313b79114e66796f934afeb96781f90f4717e6a4cc2534

// Canonical Reference: COS-OBJ-011 (blueprint.runtime.artifact)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440310
// Layer: COS
// Type: object

using System;
using System.Collections.Generic;

namespace Blueprint.COS
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
