// Checksum: 0db9b1ffa072022fcc79528411b564686e481206c580e82f3b2377c437983480

// Canonical Reference: BEA-BR-004 (blueprint.rule.contract_compliance)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655441503
// Layer: BEA
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
