// Checksum: fb9f944c6cce416beee10640facb9316fe0f63a4a82db6991d3a9ad152baf429

// Canonical Reference: COS-FB-001 (blueprint.forbidden.cos_violation)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655442200
// Layer: COS
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.COS
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
