// Checksum: d6e4285ba6fe9d23c70baf428b696a48075a54d56787b3c187154607ce06390f

// Canonical Reference: BEA-FB-003 (blueprint.forbidden.cyclic_dependency)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655442002
// Layer: BEA
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
