// Checksum: d77f9fd5012b6be6f8efd32d40a90caa16e9c6940fc92bc4974b09a2be95a593

// Canonical Reference: BCM-EVT-026 (blueprint.event.decision.reversed)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440725
// Layer: BCM
// Type: event

using System;
using System.Collections.Generic;

namespace Blueprint.BCM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
