// Checksum: d4d01d222568a9ae084df09908daa63d49bbac19ce0e9ee4709eb00c0b0376be

// Canonical Reference: BCM-BR-003 (blueprint.rule.evidence_evaluation)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655441602
// Layer: BCM
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BCM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
