// Checksum: b86e5d612d6b0224ec996c054abb4999601d2046ae698e13d9c76ffc912627e5

// Canonical Reference: BCM-CR-003 (blueprint.cognitive_rule.evidence)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655441802
// Layer: BCM
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BCM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
