// Checksum: 34d5e89e1415e45fecf9659e4463ea8f8ae017dbe21658fc55d738ed4d614a62

// Canonical Reference: BEA-CONTRACT-001 (blueprint.contract.object)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440600
// Layer: BEA
// Type: contract

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
