// Checksum: 3761cc941b7696c1ff8f15fe99869b54344a4acc4fa097c7c755b1a2bc976ca9

// Canonical Reference: BCM-CR-002 (blueprint.cognitive_rule.perception)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655441801
// Layer: BCM
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.BCM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
