// Checksum: 04fb41e5120fbdd003e59b226e8582480e57a43607f52d36b734bdfbdb85d900

// Canonical Reference: BCM-EVT-004 (blueprint.event.perception.created)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440703
// Layer: BCM
// Type: event

using System;
using System.Collections.Generic;

namespace Blueprint.BCM
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Chief Cognitive Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
