// Checksum: f2e09f807a884e8e05ebf39074f8c4474376855667e3829682e211f9c687a718

// Canonical Reference: COS-INV-005 (blueprint.invariant.runtime_loop_determinism)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655441304
// Layer: COS
// Type: unknown

using System;
using System.Collections.Generic;

namespace Blueprint.COS
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "COS Team";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
