// Checksum: 2e4b4da9291dfdd99ca767dde8bff0ebde18b9349a3a1d1bbdc99c57af5bccf1

// Canonical Reference: BEA-CONTRACT-003 (blueprint.contract.runtime)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440602
// Layer: BEA
// Type: contract

using System;
using System.Collections.Generic;

namespace Blueprint.BEA
{
    public class 
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
        public Dictionary<string, object> Extra { get; set; }

        public ()
        {
            Id = Guid.NewGuid().ToString();
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }

        public (string name)
        {
            Id = Guid.NewGuid().ToString();
            Name = name;
            Owner = "Enterprise Chief Architect";
            Version = "1.0.0";
            Extra = new Dictionary<string, object>();
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
