// Canonical Reference: BCM-OBJ-023
// Owner: Chief Cognitive Architect

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Context {
    pub id: String,
    pub name: String,
    pub owner: String,
    pub version: String,
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
