// Canonical Reference: COS-OBJ-007
// Owner: COS Team

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Policy {
    pub id: String,
    pub name: String,
    pub owner: String,
    pub version: String,
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
