// Canonical Reference: BEA-OBJ-001
// Owner: Enterprise Chief Architect

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Version {
    pub id: String,
    pub name: String,
    pub owner: String,
    pub version: String,
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
