export type IntegrityInvariantId =
  | "PLAYBACK_MONOTONIC_TIME"
  | "PLAYBACK_FRAME_ORDER"
  | "SNAPSHOT_HASH_MATCH"
  | "SNAPSHOT_EQUIVALENCE"
  | "GRAPH_NO_CYCLE"
  | "GRAPH_STABLE_TOPOLOGY"
  | "MERGE_PARENT_VALID"
  | "SESSION_HASH_VALID"
  | "RENDERER_LAYOUT_STABLE";
