// Canonical Reference: BCM-GRAPH-005
// Owner: Chief Cognitive Architect

package com.blueprint.cvm;

public class KnowledgeGraph {
    private String id;
    private String name;
    private String owner;
    private String version;

    public KnowledgeGraph() {}

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getOwner() { return owner; }
    public void setOwner(String owner) { this.owner = owner; }
    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
