// Checksum: 737868420b94117c15541474e3f80f241796aa3c21dd8b87c42fb50a4c5244d8

// Canonical Reference: CVM-OBJ-002 (blueprint.execution.budget)
// Owner: CVM Team
// UUID: 600e8400-e29b-41d4-a716-446655440401
// Layer: CVM
// Type: object

package com.blueprint.cvm

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "CVM Team",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
