// Checksum: 68a1289139c959a11f48582d0cc8bfa4171df6346a27ad8bd48487858298fcd0

// Canonical Reference: COS-OBJ-010 (blueprint.runtime.featureflag)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440309
// Layer: COS
// Type: object

package com.blueprint.cos

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "COS Team",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
