// Checksum: 074aea92829b38348671b56f9900f2faf67d621954891857a6c808580835cac7

// Canonical Reference: BEA-FB-001 (blueprint.forbidden.duplicate_definitions)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655442000
// Layer: BEA
// Type: unknown

package com.blueprint.bea

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "Enterprise Chief Architect",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
