// Checksum: dcc42d25a916f1254c7f918b23ca067285b9bbc48aa7f888c29b670fa7f0fdd6

// Canonical Reference: COS-OBJ-009 (blueprint.runtime.query)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440308
// Layer: COS
// Type: object

package com.blueprint.cos

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "COS Team",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
