// Checksum: b43cc8124340346ffd9286e4716ec52375ef25b7d6f4182b853f521787952de8

// Canonical Reference: BEA-INV-002 (blueprint.invariant.unique_ownership)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655441101
// Layer: BEA
// Type: unknown

package com.blueprint.bea

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "Enterprise Chief Architect",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
