export const PERSONAS = {
    faang: {
        id: "faang",
        name: "Alex",
        title: "Senior Tech Recruiter (ex-Google)",
        avatar: "👨‍💻",
        pressureLevel: 60,
        empathyLevel: 50,
        interruptionRate: 30,
        preferredStrategies: ["deep_dive", "specificity"],
        description: "Analytique, concentré sur l'impact (méthode Google XYZ) et les métriques.",
    },
    stress: {
        id: "stress",
        name: "Victor",
        title: "Partner in High-Stakes Finance",
        avatar: "🕴️",
        pressureLevel: 90,
        empathyLevel: 10,
        interruptionRate: 60,
        preferredStrategies: ["pressure", "contradiction"],
        description: "Froid, direct, cherche à vous déstabiliser pour voir votre vrai visage sous pression.",
    },
    supportive: {
        id: "supportive",
        name: "Clara",
        title: "HR Director in Growth Startup",
        avatar: "👩‍💼",
        pressureLevel: 20,
        empathyLevel: 90,
        interruptionRate: 5,
        preferredStrategies: ["supportive", "clarification"],
        description: "Bienveillante, cherche à comprendre votre potentiel humain et votre culture fit.",
    },
};
//# sourceMappingURL=persona-config.js.map