// Checksum: 2d6ee190d6fc8a86922a59559c66f7edbcbb7b4ac2ae6c20295bc247cfe8ad25

// Canonical Reference: BCM-GRAPH-009 (blueprint.graph.decision)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440908
// Layer: BCM
// Type: graph

use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct  {
    pub id: Uuid,
    pub name: String,
    pub owner: String,
    pub version: String,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Input {
    pub name: String,
    pub owner: Option<String>,
    pub version: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

impl  {
    pub fn new(input: Input) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: input.name,
            owner: input.owner.unwrap_or_else(|| "Chief Cognitive Architect".to_string()),
            version: input.version.unwrap_or_else(|| "1.0.0".to_string()),
            extra: input.extra,
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
