// Checksum: 4e2ea3b539481d13edc4e85fe3d071cf60a2778434db4c5c6529879f60ecf3ef

// Canonical Reference: BCM-INV-003 (blueprint.invariant.evidence_validity)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655441202
// Layer: BCM
// Type: unknown

use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct  {
    pub id: Uuid,
    pub name: String,
    pub owner: String,
    pub version: String,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Input {
    pub name: String,
    pub owner: Option<String>,
    pub version: Option<String>,
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

impl  {
    pub fn new(input: Input) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: input.name,
            owner: input.owner.unwrap_or_else(|| "Chief Cognitive Architect".to_string()),
            version: input.version.unwrap_or_else(|| "1.0.0".to_string()),
            extra: input.extra,
        }
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
