// Canonical Reference: BCM-OBJ-013
// Owner: Chief Cognitive Architect

package com.blueprint.unknown

data class Adaptation(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
