// Canonical Reference: BCM-OBJ-004
// Owner: Chief Cognitive Architect

package com.blueprint.domain

data class Confidence(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
