// Canonical Reference: BCM-OBJ-023
// Owner: Chief Cognitive Architect

package com.blueprint.unknown

data class Context(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
