// Canonical Reference: BCM-OBJ-003
// Owner: Chief Cognitive Architect

package com.blueprint.cvm

data class Evidence(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
