// Canonical Reference: BCM-OBJ-002
// Owner: Chief Cognitive Architect

package com.blueprint.bcm

data class Perception(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
