// Canonical Reference: COS-OBJ-005
// Owner: COS Team

package com.blueprint.unknown

data class Strategy(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
