// Canonical Reference: BEA-OBJ-001
// Owner: Enterprise Chief Architect

package com.blueprint.unknown

data class Version(
    val id: String,
    val name: String,
    val owner: String,
    val version: String
)

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
