import { z } from "zod";
declare const EnvServerSchema: z.ZodObject<{
    NEXT_PUBLIC_SUPABASE_URL: z.ZodString;
    SUPABASE_URL: z.ZodOptional<z.ZodString>;
    SUPABASE_ANON_KEY: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.ZodString;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodString;
    OPENAI_API_KEY: z.ZodString;
    OPENAI_BASE_URL: z.ZodOptional<z.ZodString>;
    MISTRAL_API_KEY: z.ZodString;
    ELEVENLABS_API_KEY: z.ZodOptional<z.ZodString>;
    ELEVENLABS_VOICE_ID: z.ZodOptional<z.ZodString>;
    VOICE_DEBUG: z.ZodEffects<z.ZodOptional<z.ZodString>, boolean, string | undefined>;
    STRIPE_SECRET_KEY: z.ZodString;
    STRIPE_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    STRIPE_PRICE_EARLY: z.ZodOptional<z.ZodString>;
    STRIPE_PRO_PRICE_ID: z.ZodOptional<z.ZodString>;
    STRIPE_EXPERT_PRICE_ID: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_URL: z.ZodOptional<z.ZodString>;
    UPSTASH_REDIS_REST_TOKEN: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    RESEND_API_KEY: z.ZodOptional<z.ZodString>;
    SLACK_WEBHOOK_URL: z.ZodOptional<z.ZodString>;
    IPQS_KEY: z.ZodOptional<z.ZodString>;
    ABSTRACT_KEY: z.ZodOptional<z.ZodString>;
    TURN_URL: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    CRON_SECRET: z.ZodOptional<z.ZodString>;
    POSTHOG_API_KEY: z.ZodOptional<z.ZodString>;
    DEEPGRAM_API_KEY: z.ZodOptional<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodEffects<z.ZodOptional<z.ZodString>, number, string | undefined>;
    CI: z.ZodEffects<z.ZodOptional<z.ZodString>, boolean, string | undefined>;
    STORE: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    OPENAI_API_KEY: string;
    MISTRAL_API_KEY: string;
    VOICE_DEBUG: boolean;
    STRIPE_SECRET_KEY: string;
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    CI: boolean;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    OPENAI_BASE_URL?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_PRICE_EARLY?: string | undefined;
    STRIPE_PRO_PRICE_ID?: string | undefined;
    STRIPE_EXPERT_PRICE_ID?: string | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    REDIS_URL?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    SLACK_WEBHOOK_URL?: string | undefined;
    IPQS_KEY?: string | undefined;
    ABSTRACT_KEY?: string | undefined;
    TURN_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    CRON_SECRET?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
    DEEPGRAM_API_KEY?: string | undefined;
    STORE?: string | undefined;
}, {
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    OPENAI_API_KEY: string;
    MISTRAL_API_KEY: string;
    STRIPE_SECRET_KEY: string;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    OPENAI_BASE_URL?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    VOICE_DEBUG?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_PRICE_EARLY?: string | undefined;
    STRIPE_PRO_PRICE_ID?: string | undefined;
    STRIPE_EXPERT_PRICE_ID?: string | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    REDIS_URL?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    SLACK_WEBHOOK_URL?: string | undefined;
    IPQS_KEY?: string | undefined;
    ABSTRACT_KEY?: string | undefined;
    TURN_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    CRON_SECRET?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
    DEEPGRAM_API_KEY?: string | undefined;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: string | undefined;
    CI?: string | undefined;
    STORE?: string | undefined;
}>;
export declare const envServer: {
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    OPENAI_API_KEY: string;
    MISTRAL_API_KEY: string;
    VOICE_DEBUG: boolean;
    STRIPE_SECRET_KEY: string;
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    CI: boolean;
    SUPABASE_URL?: string | undefined;
    SUPABASE_ANON_KEY?: string | undefined;
    OPENAI_BASE_URL?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    STRIPE_PRICE_EARLY?: string | undefined;
    STRIPE_PRO_PRICE_ID?: string | undefined;
    STRIPE_EXPERT_PRICE_ID?: string | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    REDIS_URL?: string | undefined;
    RESEND_API_KEY?: string | undefined;
    SLACK_WEBHOOK_URL?: string | undefined;
    IPQS_KEY?: string | undefined;
    ABSTRACT_KEY?: string | undefined;
    TURN_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    CRON_SECRET?: string | undefined;
    POSTHOG_API_KEY?: string | undefined;
    DEEPGRAM_API_KEY?: string | undefined;
    STORE?: string | undefined;
};
export type EnvServer = z.infer<typeof EnvServerSchema>;
export {};
//# sourceMappingURL=env.server.d.ts.map