// Checksum: 38c63c43ab7cfd4458496863e43ecd075aa568595142162d0a08d60b71b741c4

// Canonical Reference: BCM-OBJ-023 (blueprint.cognitive.context)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440222
// Layer: BCM
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
