// Checksum: b5d0ae31e9cefc5af7ce8a1080fa2b61c64e00ff9b123c517a8c27107740f7d3

// Canonical Reference: BCM-OBJ-005 (blueprint.cognitive.knowledge)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440204
// Layer: BCM
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
