// Checksum: 774e180f9b3e20ff482c944f7c8d7d5c34418f9d0fa45a057f9ae8fdb90c7d28

// Canonical Reference: BCM-OBJ-010 (blueprint.cognitive.plan)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440209
// Layer: BCM
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
