apiVersion: v2
name: trajectoire
description: Trajectoire application deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - trajectoire
  - api
  - nestjs
maintainers:
  - name: Trajectoire Team
    email: team@trajectoire.com
