// runtime/types/RuntimeErrorCode.ts
/**
 * Enumerates deterministic runtime error codes for precise categorisation.
 */
export enum RuntimeErrorCode {
  STATE_HASH_MISMATCH = "STATE_HASH_MISMATCH",
  REPLAY_DRIFT = "REPLAY_DRIFT",
  INVALID_SIGNAL = "INVALID_SIGNAL",
  INVALID_PHASE_TRANSITION = "INVALID_PHASE_TRANSITION",
  NON_DETERMINISTIC_OPERATION = "NON_DETERMINISTIC_OPERATION",
  DETERMINISTIC_INVARIANT_VIOLATION = "DETERMINISTIC_INVARIANT_VIOLATION",
  CAUSAL_CHAIN_VIOLATION = "CAUSAL_CHAIN_VIOLATION",
  SERIALIZATION_DRIFT = "SERIALIZATION_DRIFT",
  UNSUPPORTED_SERIALIZATION_TYPE = "UNSUPPORTED_SERIALIZATION_TYPE",
  FROZEN_STATE_MUTATION_ATTEMPT = "FROZEN_STATE_MUTATION_ATTEMPT",
  DUPLICATE_STEP_HASH = "DUPLICATE_STEP_HASH",
  CYCLIC_CAUSAL_GRAPH = "CYCLIC_CAUSAL_GRAPH",
  REPLAY_CHECKSUM_MISMATCH = "REPLAY_CHECKSUM_MISMATCH",

  // Existing members retained below
  // Note: duplicated entries will be removed by later cleanup if needed
}
