// Canonical Reference: COS-OBJ-011
// Owner: COS Team

package blueprint

type Artifact struct {
    ID      string `json:"id"`
    Name    string `json:"name"`
    Owner   string `json:"owner"`
    Version string `json:"version"`
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
