// Canonical Reference: COS-OBJ-006
// Owner: COS Team

package blueprint

type Capability struct {
    ID      string `json:"id"`
    Name    string `json:"name"`
    Owner   string `json:"owner"`
    Version string `json:"version"`
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
