// Canonical Reference: BCM-OBJ-002
// Owner: Chief Cognitive Architect

package blueprint

type Perception struct {
    ID      string `json:"id"`
    Name    string `json:"name"`
    Owner   string `json:"owner"`
    Version string `json:"version"`
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
