// Canonical Reference: BEA-INV-008
// Owner: Enterprise Chief Architect

package blueprint

type Traceability struct {
    ID      string `json:"id"`
    Name    string `json:"name"`
    Owner   string `json:"owner"`
    Version string `json:"version"`
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
