// Checksum: 7f046022f1433688db56be7491341d00ef5bf5f5401425d5120ca327a469076e

// Canonical Reference: COS-CR-001 (blueprint.cognitive_rule.cos)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655441900
// Layer: COS
// Type: unknown

package blueprint

import (
    "github.com/google/uuid"
)

type  struct {
    ID      string                 `json:"id"`
    Name    string                 `json:"name"`
    Owner   string                 `json:"owner"`
    Version string                 `json:"version"`
    Extra   map[string]interface{} `json:"extra"`
}

type Input struct {
    Name    string                 `json:"name"`
    Owner   *string                `json:"owner,omitempty"`
    Version *string                `json:"version,omitempty"`
    Extra   map[string]interface{} `json:"extra,omitempty"`
}

func New(input Input) * {
    owner := "COS Team"
    if input.Owner != nil {
        owner = *input.Owner
    }
    
    version := "1.0.0"
    if input.Version != nil {
        version = *input.Version
    }
    
    return &{
        ID:      uuid.New().String(),
        Name:    input.Name,
        Owner:   owner,
        Version: version,
        Extra:   input.Extra,
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
