// Checksum: 3b06f593b61322a0d07c9df6ab04cc187a6e21f623804d2f0ed29a546f4698cb

// Canonical Reference: BEA-CONTRACT-010 (blueprint.contract.security)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440610
// Layer: BEA
// Type: contract

package blueprint

import (
    "github.com/google/uuid"
)

type  struct {
    ID      string                 `json:"id"`
    Name    string                 `json:"name"`
    Owner   string                 `json:"owner"`
    Version string                 `json:"version"`
    Extra   map[string]interface{} `json:"extra"`
}

type Input struct {
    Name    string                 `json:"name"`
    Owner   *string                `json:"owner,omitempty"`
    Version *string                `json:"version,omitempty"`
    Extra   map[string]interface{} `json:"extra,omitempty"`
}

func New(input Input) * {
    owner := "Enterprise Chief Architect"
    if input.Owner != nil {
        owner = *input.Owner
    }
    
    version := "1.0.0"
    if input.Version != nil {
        version = *input.Version
    }
    
    return &{
        ID:      uuid.New().String(),
        Name:    input.Name,
        Owner:   owner,
        Version: version,
        Extra:   input.Extra,
    }
}

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
