// Checksum: 751c6a292ea777f1a87ffa0a86dc9a22da6475621acab44bab2233afebd55cdc

// Canonical Reference: COS-OBJ-002 (blueprint.runtime.conversation)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440301
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
