// Checksum: 1cadba51e4d42237da0b9302fbdaf21389cea1aac43e2f1887a3551610edf90e

// Canonical Reference: BCM-OBJ-021 (blueprint.cognitive.node)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440220
// Layer: BCM
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
