// Checksum: 477e3720578ed73145d2614627402b52020998041115a0159f284e3e484edf26

// Canonical Reference: BEA-OBJ-002 (blueprint.system.package)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440501
// Layer: BEA
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
