// Checksum: 98e802466d77c8a511535bd5ce6fa58c81130ba62849c69ce473dea01889fb4a

// Canonical Reference: COS-OBJ-007 (blueprint.runtime.policy)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440306
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
