// Checksum: a51ac892407a6ffe2f2d96f959bad64dff6f3f154d82e94c917990853c4e32be

// Canonical Reference: COS-OBJ-005 (blueprint.runtime.strategy)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440304
// Layer: COS
// Type: object

export interface undefined {
  // Properties generated from canonical model
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: any;
}

export type undefinedInput = Omit<undefined, 'id'>;

export type undefinedUpdate = Partial<undefinedInput>;

/*
 * This file is auto-generated by the Blueprint Canonical Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
