/**
 * Blueprint DSL Bytecode Verifier
 * 
 * Verifies the correctness of generated bytecode.
 */

import { BytecodeModule, BytecodeFunction, BytecodeInstruction, BytecodeOpcode } from './bytecode-generator';

export interface VerificationError {
  message: string;
  function?: string;
  instructionIndex?: number;
  severity: 'error' | 'warning';
}

export interface VerificationResult {
  errors: VerificationError[];
  warnings: VerificationError[];
  success: boolean;
}

export class BytecodeVerifier {
  private errors: VerificationError[] = [];
  private warnings: VerificationError[] = [];

  /**
   * Verify a bytecode module
   */
  public verify(bytecode: BytecodeModule): VerificationResult {
    this.errors = [];
    this.warnings = [];

    this.verifyHeader(bytecode);
    this.verifyFunctions(bytecode);
    this.verifyMetadata(bytecode);

    return {
      errors: this.errors,
      warnings: this.warnings,
      success: this.errors.length === 0,
    };
  }

  /**
   * Verify the bytecode header
   */
  private verifyHeader(bytecode: BytecodeModule): void {
    if (!bytecode.version) {
      this.addError('Missing version in bytecode header');
    }

    if (!bytecode.version.match(/^\d+\.\d+\.\d+$/)) {
      this.addError('Invalid version format in bytecode header');
    }
  }

  /**
   * Verify all functions
   */
  private verifyFunctions(bytecode: BytecodeModule): void {
    const functionNames = new Set<string>();

    for (const func of bytecode.functions) {
      // Check for duplicate function names
      if (functionNames.has(func.name)) {
        this.addError(`Duplicate function name: ${func.name}`, func.name);
      }
      functionNames.add(func.name);

      this.verifyFunction(func);
    }
  }

  /**
   * Verify a single function
   */
  private verifyFunction(func: BytecodeFunction): void {
    if (!func.name) {
      this.addError('Function missing name', func.name);
    }

    if (func.parameterCount < 0) {
      this.addError(`Invalid parameter count: ${func.parameterCount}`, func.name);
    }

    if (func.localCount < 0) {
      this.addError(`Invalid local count: ${func.localCount}`, func.name);
    }

    this.verifyInstructions(func);
    this.verifyConstants(func);
  }

  /**
   * Verify instructions in a function
   */
  private verifyInstructions(func: BytecodeFunction): void {
    for (let i = 0; i < func.bytecode.length; i++) {
      const instruction = func.bytecode[i];
      this.verifyInstruction(instruction, func.name, i);
    }

    this.verifyControlFlow(func);
  }

  /**
   * Verify a single instruction
   */
  private verifyInstruction(instruction: BytecodeInstruction, functionName: string, index: number): void {
    this.verifyOpcode(instruction, functionName, index);
    this.verifyOperands(instruction, functionName, index);
  }

  /**
   * Verify the opcode
   */
  private verifyOpcode(instruction: BytecodeInstruction, functionName: string, index: number): void {
    const validOpcodes = Object.values(BytecodeOpcode);
    
    if (!validOpcodes.includes(instruction.opcode)) {
      this.addError(
        `Invalid opcode: ${instruction.opcode}`,
        functionName,
        index
      );
    }
  }

  /**
   * Verify the operands
   */
  private verifyOperands(instruction: BytecodeInstruction, functionName: string, index: number): void {
    const expectedOperandCount = this.getExpectedOperandCount(instruction.opcode);
    
    if (instruction.operands.length !== expectedOperandCount) {
      this.addError(
        `Invalid operand count: expected ${expectedOperandCount}, got ${instruction.operands.length}`,
        functionName,
        index
      );
    }

    for (let i = 0; i < instruction.operands.length; i++) {
      const operand = instruction.operands[i];
      
      if (typeof operand !== 'number' || !Number.isInteger(operand)) {
        this.addError(
          `Invalid operand at index ${i}: must be an integer`,
          functionName,
          index
        );
      }

      if (operand < 0) {
        this.addError(
          `Invalid operand at index ${i}: must be non-negative`,
          functionName,
          index
        );
      }
    }
  }

  /**
   * Get the expected operand count for an opcode
   */
  private getExpectedOperandCount(opcode: BytecodeOpcode): number {
    switch (opcode) {
      case BytecodeOpcode.RET:
        return 0;
      case BytecodeOpcode.DUP:
      case BytecodeOpcode.POP:
        return 1;
      case BytecodeOpcode.NOT:
        return 2;
      case BytecodeOpcode.ADD:
      case BytecodeOpcode.SUB:
      case BytecodeOpcode.MUL:
      case BytecodeOpcode.DIV:
      case BytecodeOpcode.MOD:
      case BytecodeOpcode.AND:
      case BytecodeOpcode.OR:
      case BytecodeOpcode.XOR:
      case BytecodeOpcode.SHL:
      case BytecodeOpcode.SHR:
        return 3;
      case BytecodeOpcode.LOAD:
      case BytecodeOpcode.STORE:
      case BytecodeOpcode.LOAD_CONST:
      case BytecodeOpcode.BR:
        return 2;
      case BytecodeOpcode.CALL:
      case BytecodeOpcode.BR_COND:
        return 3;
      case BytecodeOpcode.COGNITIVE_REASONING:
      case BytecodeOpcode.COGNITIVE_INFERENCE:
      case BytecodeOpcode.COGNITIVE_HYPOTHESIS:
      case BytecodeOpcode.COGNITIVE_KNOWLEDGE:
      case BytecodeOpcode.COGNITIVE_MEMORY:
      case BytecodeOpcode.PROVIDER_CALL:
        return 2;
      default:
        return 0;
    }
  }

  /**
   * Verify control flow in a function
   */
  private verifyControlFlow(func: BytecodeFunction): void {
    let hasReturn = false;

    for (const instruction of func.bytecode) {
      if (instruction.opcode === BytecodeOpcode.RET) {
        hasReturn = true;
      }
    }

    if (!hasReturn) {
      this.addWarning(`Function '${func.name}' does not have a return instruction`, func.name);
    }

    // Verify branch targets
    for (let i = 0; i < func.bytecode.length; i++) {
      const instruction = func.bytecode[i];
      
      if (instruction.opcode === BytecodeOpcode.BR || instruction.opcode === BytecodeOpcode.BR_COND) {
        if (instruction.operands.length > 0) {
          const target = instruction.operands[instruction.operands.length - 1];
          
          if (target < 0 || target >= func.bytecode.length) {
            this.addError(
              `Invalid branch target: ${target}`,
              func.name,
              i
            );
          }
        }
      }
    }
  }

  /**
   * Verify constants in a function
   */
  private verifyConstants(func: BytecodeFunction): void {
    for (let i = 0; i < func.constants.length; i++) {
      const constant = func.constants[i];
      
      if (constant === undefined || constant === null) {
        this.addWarning(`Constant at index ${i} is null or undefined`, func.name);
      }
    }
  }

  /**
   * Verify metadata
   */
  private verifyMetadata(bytecode: BytecodeModule): void {
    if (!bytecode.metadata) {
      this.addError('Missing metadata in bytecode module');
      return;
    }

    if (!bytecode.metadata.sourceFile) {
      this.addWarning('Missing source file in metadata');
    }

    if (!bytecode.metadata.compilerVersion) {
      this.addWarning('Missing compiler version in metadata');
    }

    if (bytecode.metadata.compilationTime <= 0) {
      this.addWarning('Invalid compilation time in metadata');
    }
  }

  /**
   * Add an error
   */
  private addError(message: string, functionName?: string, instructionIndex?: number): void {
    this.errors.push({
      message,
      function: functionName,
      instructionIndex,
      severity: 'error',
    });
  }

  /**
   * Add a warning
   */
  private addWarning(message: string, functionName?: string, instructionIndex?: number): void {
    this.warnings.push({
      message,
      function: functionName,
      instructionIndex,
      severity: 'warning',
    });
  }
}
