// Canonical Reference: CVM-OBJ-001
// Owner: CVM Team

using System;

namespace Blueprint.UNKNOWN
{
    public class Execution
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
    }
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
