// Canonical Reference: BCM-OBJ-005
// Owner: Chief Cognitive Architect

using System;

namespace Blueprint.UNKNOWN
{
    public class Knowledge
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
    }
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
