// Canonical Reference: BEA-OBJ-002
// Owner: Enterprise Chief Architect

using System;

namespace Blueprint.UNKNOWN
{
    public class Package
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Version { get; set; }
    }
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 */
