// Checksum: 5b385579b68201d56fdd10b55ac7e8fb27134a3b52a9f5af0198c79172518c14

// Canonical Reference: COS-OBJ-006 (blueprint.runtime.capability)
// Owner: COS Team
// UUID: 600e8400-e29b-41d4-a716-446655440305
// Layer: COS
// Type: object

package com.blueprint.cos

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "COS Team",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
