// Checksum: 7b613c41203b71095c6eeb11a0c53e293bf4590136378960299da93ef977cac1

// Canonical Reference: CVM-OBJ-001 (blueprint.execution.execution)
// Owner: CVM Team
// UUID: 600e8400-e29b-41d4-a716-446655440400
// Layer: CVM
// Type: object

package com.blueprint.cvm

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "CVM Team",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
