// Checksum: 060dd751e391196145f19be08fc1da01055954fdf12a42186ed138a331f1b435

// Canonical Reference: BCM-EVT-020 (blueprint.event.hypothesis.rejected)
// Owner: Chief Cognitive Architect
// UUID: 600e8400-e29b-41d4-a716-446655440719
// Layer: BCM
// Type: event

package com.blueprint.bcm

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "Chief Cognitive Architect",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
