// Checksum: 83064b3acc077a0d5a48843569d0001bb2e43a1daccd343dcf61cbc24f541d95

// Canonical Reference: BEA-OBJ-001 (blueprint.system.version)
// Owner: Enterprise Chief Architect
// UUID: 600e8400-e29b-41d4-a716-446655440500
// Layer: BEA
// Type: object

package com.blueprint.bea

import java.util.UUID

data class (
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val owner: String = "Enterprise Chief Architect",
    val version: String = "1.0.0",
    val extra: Map<String, Any> = emptyMap()
)

/*
 * This file is auto-generated by the Blueprint Multi-Language Generator.
 * Do not edit manually. All changes will be overwritten.
 */
