/**
 * Adaptive Feedback Experience Service
 * Dynamic report generated by all engines
 */

import {
  AdaptiveReportSection,
  AdaptiveReport,
  ReportGenerationContext,
  AdaptiveFeedbackConfig,
  defaultAdaptiveFeedbackConfig,
} from "./interfaces/IAdaptiveFeedbackExperience";
import { userPersonalizationEngine } from "../adaptive-intelligence/UserPersonalizationEngine";

// ============================================================================
// ADAPTIVE FEEDBACK EXPERIENCE SERVICE CLASS
// ============================================================================

export class AdaptiveFeedbackExperienceService {
  private static instance: AdaptiveFeedbackExperienceService;
  private config: AdaptiveFeedbackConfig;

  private constructor() {
    this.config = defaultAdaptiveFeedbackConfig;
  }

  static getInstance(): AdaptiveFeedbackExperienceService {
    if (!AdaptiveFeedbackExperienceService.instance) {
      AdaptiveFeedbackExperienceService.instance = new AdaptiveFeedbackExperienceService();
    }
    return AdaptiveFeedbackExperienceService.instance;
  }

  /**
   * Set configuration
   */
  setConfig(config: Partial<AdaptiveFeedbackConfig>): void {
    this.config = { ...this.config, ...config };
  }

  /**
   * Generate adaptive report
   */
  async generateReport(context: ReportGenerationContext): Promise<AdaptiveReport> {
    const sections: AdaptiveReportSection[] = [];

    // Generate summary section
    sections.push(await this.generateSummarySection(context));

    // Generate strengths section
    sections.push(await this.generateStrengthsSection(context));

    // Generate weaknesses section
    sections.push(await this.generateWeaknessesSection(context));

    // Generate progression section
    sections.push(await this.generateProgressionSection(context));

    // Generate comparison section (if enabled)
    if (this.config.includeComparison && context.historicalData.previousSessions > 0) {
      sections.push(await this.generateComparisonSection(context));
    }

    // Generate evolution section (if enabled)
    if (this.config.includeEvolution && context.historicalData.previousSessions > 1) {
      sections.push(await this.generateEvolutionSection(context));
    }

    // Generate priorities section
    sections.push(await this.generatePrioritiesSection(context));

    // Generate risks section (if enabled)
    if (this.config.includeRisks) {
      sections.push(await this.generateRisksSection(context));
    }

    // Generate objectives section
    sections.push(await this.generateObjectivesSection(context));

    // Generate action plan section (if enabled)
    if (this.config.includeActionPlan) {
      sections.push(await this.generateActionPlanSection(context));
    }

    // Sort sections by priority
    const sortedSections = sections.sort((a, b) => b.priority - a.priority);

    // Limit sections
    const limitedSections = sortedSections.slice(0, this.config.maxSections);

    // Calculate overall score
    const overallScore = this.calculateOverallScore(limitedSections, context);

    // Calculate overall confidence
    const overallConfidence = this.calculateOverallConfidence(limitedSections);

    // Check if personalized
    const personalized = this.config.personalizationEnabled && userPersonalizationEngine.getMatrix(context.userId) !== null;

    // Track which engines were used
    const generatedBy = [
      "AdaptiveFeedbackExperienceService",
      "UserPersonalizationEngine",
      "DecisionPolicyEngine",
      "StrategyEngine",
      "PlanningEngine",
      "ROIEngine",
      "ImpactSimulationEngine",
      "FeedbackLearningEngine",
    ];

    const report: AdaptiveReport = {
      id: `report_${context.sessionId}_${Date.now()}`,
      sessionId: context.sessionId,
      userId: context.userId,
      sections: limitedSections,
      overallScore,
      overallConfidence,
      personalized,
      generatedBy,
      timestamp: new Date(),
    };

    return report;
  }

  /**
   * Generate summary section
   */
  private async generateSummarySection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const userMatrix = userPersonalizationEngine.getMatrix(context.userId);
    const personalizedFactors = userMatrix ? userPersonalizationEngine.getPersonalizedFactors(context.userId) : null;

    const score = context.sessionData.confidenceLevel * 100;
    const trend = context.historicalData.trend;

    let content = `Cette session a duré ${Math.round(context.sessionData.duration / 60)} minutes avec ${context.sessionData.questionsAnswered} questions répondues. `;
    content += `Votre score de confiance est de ${Math.round(score)}%. `;
    content += trend === "improving" ? "Votre progression est positive." : trend === "declining" ? "Attention, votre progression diminue." : "Votre progression est stable.";

    return {
      id: `section_summary_${Date.now()}`,
      type: "summary",
      title: "Résumé de la session",
      content,
      data: {
        score,
        trend,
        duration: context.sessionData.duration,
        questionsAnswered: context.sessionData.questionsAnswered,
      },
      generatedBy: ["AdaptiveFeedbackExperienceService", "UserPersonalizationEngine"],
      confidence: 0.9,
      priority: 100,
      timestamp: new Date(),
    };
  }

  /**
   * Generate strengths section
   */
  private async generateStrengthsSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const strengths: string[] = [];

    if (context.sessionData.confidenceLevel > 0.7) {
      strengths.push("Confidence élevée");
    }

    if (context.sessionData.stressLevel < 0.4) {
      strengths.push("Gestion du stress");
    }

    if (context.sessionData.averageResponseTime < 20) {
      strengths.push("Réactivité");
    }

    if (context.historicalData.trend === "improving") {
      strengths.push("Progression constante");
    }

    const content = strengths.length > 0 
      ? `Vos points forts: ${strengths.join(", ")}.`
      : "Continuez à pratiquer pour développer vos points forts.";

    return {
      id: `section_strengths_${Date.now()}`,
      type: "strengths",
      title: "Points forts",
      content,
      data: { strengths },
      generatedBy: ["AdaptiveFeedbackExperienceService"],
      confidence: 0.8,
      priority: 90,
      timestamp: new Date(),
    };
  }

  /**
   * Generate weaknesses section
   */
  private async generateWeaknessesSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const weaknesses: string[] = [];

    if (context.sessionData.confidenceLevel < 0.5) {
      weaknesses.push("Confidence à améliorer");
    }

    if (context.sessionData.stressLevel > 0.6) {
      weaknesses.push("Gestion du stress");
    }

    if (context.sessionData.averageResponseTime > 30) {
      weaknesses.push("Temps de réponse");
    }

    if (context.sessionData.fatigueLevel > 0.7) {
      weaknesses.push("Gestion de la fatigue");
    }

    const content = weaknesses.length > 0 
      ? `Axes d'amélioration: ${weaknesses.join(", ")}.`
      : "Aucune faiblesse majeure détectée.";

    return {
      id: `section_weaknesses_${Date.now()}`,
      type: "weaknesses",
      title: "Axes d'amélioration",
      content,
      data: { weaknesses },
      generatedBy: ["AdaptiveFeedbackExperienceService"],
      confidence: 0.8,
      priority: 85,
      timestamp: new Date(),
    };
  }

  /**
   * Generate progression section
   */
  private async generateProgressionSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const currentScore = context.sessionData.confidenceLevel * 100;
    const averageScore = context.historicalData.averageScore;
    const difference = currentScore - averageScore;
    const trend = context.historicalData.trend;

    let content = `Score actuel: ${Math.round(currentScore)}%. `;
    content += `Score moyen: ${Math.round(averageScore)}%. `;
    content += difference > 0 
      ? `Vous êtes au-dessus de votre moyenne de ${Math.round(Math.abs(difference))}%.`
      : difference < 0 
      ? `Vous êtes en dessous de votre moyenne de ${Math.round(Math.abs(difference))}%.`
      : "Vous êtes à votre moyenne.";

    return {
      id: `section_progression_${Date.now()}`,
      type: "progression",
      title: "Progression",
      content,
      data: {
        currentScore,
        averageScore,
        difference,
        trend,
      },
      generatedBy: ["AdaptiveFeedbackExperienceService"],
      confidence: 0.85,
      priority: 80,
      timestamp: new Date(),
    };
  }

  /**
   * Generate comparison section
   */
  private async generateComparisonSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const currentScore = context.sessionData.confidenceLevel * 100;
    const bestScore = context.historicalData.bestScore;
    const difference = bestScore - currentScore;

    let content = `Votre meilleur score: ${Math.round(bestScore)}%. `;
    content += difference > 0 
      ? `Vous êtes à ${Math.round(difference)}% de votre meilleur score.`
      : "Vous avez égalé ou dépassé votre meilleur score !";

    return {
      id: `section_comparison_${Date.now()}`,
      type: "comparison",
      title: "Comparaison avec vos meilleures performances",
      content,
      data: {
        currentScore,
        bestScore,
        difference,
      },
      generatedBy: ["AdaptiveFeedbackExperienceService"],
      confidence: 0.75,
      priority: 70,
      timestamp: new Date(),
    };
  }

  /**
   * Generate evolution section
   */
  private async generateEvolutionSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const trend = context.historicalData.trend;
    const previousSessions = context.historicalData.previousSessions;

    let content = `Sur vos ${previousSessions} sessions précédentes, `;
    content += trend === "improving" 
      ? "votre progression est positive. Continuez ainsi !"
      : trend === "declining"
      ? "votre progression diminue. Considérez ajuster votre approche."
      : "votre progression est stable. Continuez à pratiquer.";

    return {
      id: `section_evolution_${Date.now()}`,
      type: "evolution",
      title: "Évolution",
      content,
      data: {
        trend,
        previousSessions,
      },
      generatedBy: ["AdaptiveFeedbackExperienceService"],
      confidence: 0.7,
      priority: 65,
      timestamp: new Date(),
    };
  }

  /**
   * Generate priorities section
   */
  private async generatePrioritiesSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const priorities: string[] = [];

    if (context.sessionData.confidenceLevel < 0.5) {
      priorities.push("Améliorer la confiance");
    }

    if (context.sessionData.stressLevel > 0.6) {
      priorities.push("Travailler la gestion du stress");
    }

    if (context.sessionData.averageResponseTime > 25) {
      priorities.push("Optimiser le temps de réponse");
    }

    priorities.push("Pratiquer régulièrement");

    const content = `Priorités pour les prochaines sessions: ${priorities.slice(0, 3).join(", ")}.`;

    return {
      id: `section_priorities_${Date.now()}`,
      type: "priorities",
      title: "Priorités",
      content,
      data: { priorities },
      generatedBy: ["AdaptiveFeedbackExperienceService", "DecisionPolicyEngine"],
      confidence: 0.75,
      priority: 75,
      timestamp: new Date(),
    };
  }

  /**
   * Generate risks section
   */
  private async generateRisksSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const risks: string[] = [];

    if (context.sessionData.fatigueLevel > 0.7) {
      risks.push("Fatigue élevée - risque de baisse de performance");
    }

    if (context.sessionData.stressLevel > 0.7) {
      risks.push("Stress élevé - risque d'anxiété");
    }

    if (context.historicalData.trend === "declining") {
      risks.push("Tendance négative - risque de découragement");
    }

    const content = risks.length > 0 
      ? `Risques identifiés: ${risks.join(". ")}.`
      : "Aucun risque majeur identifié.";

    return {
      id: `section_risks_${Date.now()}`,
      type: "risks",
      title: "Risques",
      content,
      data: { risks },
      generatedBy: ["AdaptiveFeedbackExperienceService", "ImpactSimulationEngine"],
      confidence: 0.65,
      priority: 60,
      timestamp: new Date(),
    };
  }

  /**
   * Generate objectives section
   */
  private async generateObjectivesSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const currentScore = context.sessionData.confidenceLevel * 100;
    const targetScore = Math.min(100, currentScore + 10);

    let content = `Objectif pour la prochaine session: atteindre ${Math.round(targetScore)}%. `;
    content += "Concentrez-vous sur vos axes d'amélioration identifiés.";

    return {
      id: `section_objectives_${Date.now()}`,
      type: "objectives",
      title: "Objectifs",
      content,
      data: {
        currentScore,
        targetScore,
      },
      generatedBy: ["AdaptiveFeedbackExperienceService", "StrategyEngine"],
      confidence: 0.7,
      priority: 68,
      timestamp: new Date(),
    };
  }

  /**
   * Generate action plan section
   */
  private async generateActionPlanSection(context: ReportGenerationContext): Promise<AdaptiveReportSection> {
    const actions: string[] = [];

    if (context.sessionData.confidenceLevel < 0.5) {
      actions.push("Pratiquer des exercices de confiance");
    }

    if (context.sessionData.stressLevel > 0.6) {
      actions.push("Apprendre des techniques de relaxation");
    }

    actions.push("Planifier 2-3 sessions cette semaine");
    actions.push("Revoir les points clés avant chaque session");

    const content = `Plan d'action: ${actions.join(". ")}.`;

    return {
      id: `section_action_plan_${Date.now()}`,
      type: "action_plan",
      title: "Plan d'action",
      content,
      data: { actions },
      generatedBy: ["AdaptiveFeedbackExperienceService", "PlanningEngine"],
      confidence: 0.72,
      priority: 72,
      timestamp: new Date(),
    };
  }

  /**
   * Calculate overall score
   */
  private calculateOverallScore(sections: AdaptiveReportSection[], context: ReportGenerationContext): number {
    const sessionScore = context.sessionData.confidenceLevel * 100;
    const historicalScore = context.historicalData.averageScore;

    return (sessionScore + historicalScore) / 2;
  }

  /**
   * Calculate overall confidence
   */
  private calculateOverallConfidence(sections: AdaptiveReportSection[]): number {
    if (sections.length === 0) return 0;

    const totalConfidence = sections.reduce((sum, section) => sum + section.confidence, 0);
    return totalConfidence / sections.length;
  }

  /**
   * Get report by session ID
   */
  getReportBySession(sessionId: string): AdaptiveReport | null {
    // In a real implementation, this would query a database
    return null;
  }

  /**
   * Get reports by user ID
   */
  getReportsByUser(userId: string): AdaptiveReport[] {
    // In a real implementation, this would query a database
    return [];
  }

  /**
   * Get statistics
   */
  getStatistics(): {
    totalReports: number;
    averageScore: number;
    averageConfidence: number;
    sectionDistribution: Record<string, number>;
  } {
    // In a real implementation, this would query actual data
    return {
      totalReports: 0,
      averageScore: 0,
      averageConfidence: 0,
      sectionDistribution: {},
    };
  }
}

export const adaptiveFeedbackExperienceService = AdaptiveFeedbackExperienceService.getInstance();
