// Canonical Reference: COS-OBJ-011
// Owner: COS Team
// UUID: undefined
// Layer: UNKNOWN
// Type: section

export interface Artifact {
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: unknown;
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
