// Canonical Reference: CVM-OBJ-002
// Owner: CVM Team
// UUID: undefined
// Layer: UNKNOWN
// Type: section

export interface Budget {
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: unknown;
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
