// Canonical Reference: COS-OBJ-006
// Owner: COS Team
// UUID: undefined
// Layer: CVM
// Type: struct

export interface Capability {
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: unknown;
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
