// Canonical Reference: BCM-OBJ-009
// Owner: Chief Cognitive Architect
// UUID: undefined
// Layer: CVM
// Type: struct

export interface Decision {
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: unknown;
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
