// Canonical Reference: BEA-INV-008
// Owner: Enterprise Chief Architect
// UUID: undefined
// Layer: UNKNOWN
// Type: interface

export interface Traceability {
  id: string;
  name: string;
  owner: string;
  version: string;
  [key: string]: unknown;
}

/*
 * This file is auto-generated by the Blueprint Incremental Compiler.
 * Do not edit manually. All changes will be overwritten.
 */
